Repository node-red-quantum/node-red-contrib-quantum, pull requests merged in 2021-07, with the labels that each got.

#1 Add node for executing Python code
  package.json
  quantum/python-shell.js
  quantum/terra/execute/execute.html
  quantum/terra/execute/execute.js
  quantum/terra/quantum-circuit/quantum-circuit.js
Labels: enhancement

#3 Theo/initialisation
  package.json
  quantum/terra/classical-register/classical-register.html
  quantum/terra/classical-register/classical-register.js
  quantum/terra/quantum-circuit/quantum-circuit.html
  quantum/terra/quantum-circuit/quantum-circuit.js
  quantum/terra/quantum-circuit/quantum-circuit.py
  quantum/terra/quantum-register/quantum-register.html
  quantum/terra/quantum-register/quantum-register.js
Labels: enhancement

#2 Remove redundant node directories
  package.json
  quantum/aer/.keep
  quantum/aqua/.keep
  quantum/ignis/.keep
  quantum/nodes/aer-simulator/aer-simulator.html
  quantum/nodes/aer-simulator/aer-simulator.js
  quantum/nodes/classical-register/classical-register.html
  quantum/nodes/classical-register/classical-register.js
  quantum/nodes/execute/execute.html
  quantum/nodes/execute/execute.js
  quantum/nodes/quantum-circuit/quantum-circuit.html
  quantum/nodes/quantum-circuit/quantum-circuit.js
  quantum/nodes/quantum-register/quantum-register.html
  quantum/nodes/quantum-register/quantum-register.js
Labels: refactoring

#8 Add PythonShell class
  package-lock.json
  package.json
  quantum/nodes/execute/execute.js
  quantum/python-shell.js
  quantum/python.js
Labels: enhancement

#10 Timur/measurement
  package.json
  quantum/nodes/classical-register/classical-register.html
  quantum/nodes/classical-register/classical-register.js
  quantum/nodes/measurement/measurement.html
  quantum/nodes/measurement/measurement.js
Labels: enhancement

#15 Louis/install-script
  README.md
  bin/link.sh
  bin/pyvenv.py
  bin/pyvenv.sh
  package.json
Labels: enhancement

#16 Theo/initialisation
  quantum/nodes/classical-register/classical-register.js
  quantum/nodes/quantum-circuit/quantum-circuit.html
  quantum/nodes/quantum-circuit/quantum-circuit.js
  quantum/nodes/quantum-register/quantum-register.js
  quantum/snippets.js
Labels: enhancement, refactoring

#19 Louis/shell-implementation
  .eslintrc.json
  package.json
  quantum/nodes/aer-simulator/aer-simulator.html
  quantum/nodes/aer-simulator/aer-simulator.js
  quantum/nodes/classical-register/classical-register.js
  quantum/nodes/quantum-circuit/quantum-circuit.html
  quantum/nodes/quantum-circuit/quantum-circuit.js
  quantum/nodes/quantum-register/quantum-register.html
  quantum/nodes/quantum-register/quantum-register.js
  quantum/python.js
  quantum/snippets.js
Labels: bug, enhancement

#18 Theo/Quantum barrier & Identity nodes
  package.json
  quantum/nodes/barrier/barrier.html
  quantum/nodes/barrier/barrier.js
  quantum/nodes/classical-register/classical-register.js
  quantum/nodes/identity/identity.html
  quantum/nodes/identity/identity.js
  quantum/nodes/quantum-circuit/quantum-circuit.html
  quantum/nodes/quantum-register/quantum-register.js
  quantum/python.js
  quantum/snippets.js
Labels: enhancement

#5 Rui/hadamard
  package.json
  quantum/nodes/classical-register/classical-register.js
  quantum/nodes/hadamard-gate/hadamard-gate.html
  quantum/nodes/hadamard-gate/hadamard-gate.js
  quantum/nodes/quantum-register/quantum-register.js
  quantum/snippets.js
Labels: enhancement

#22 Small PR: Stronger registers code logic, should never break
  quantum/nodes/classical-register/classical-register.js
  quantum/nodes/quantum-register/quantum-register.js
Labels: bug, enhancement

#27 Louis/script-fixes
  bin/link.sh
  bin/pyvenv.py
  bin/pyvenv.sh
  package.json
Labels: enhancement

#20 Khesim/toffoli gate node
  package.json
  quantum/nodes/toffoli-gate/toffoli-gate.html
  quantum/nodes/toffoli-gate/toffoli-gate.js
  quantum/snippets.js
Labels: enhancement

#23 Zhiqiang/cnot gate
  package.json
  quantum/nodes/cnot-gate/cnot-gate.html
  quantum/nodes/cnot-gate/cnot-gate.js
  quantum/snippets.js
Labels: enhancement

#14 Chon/Notgate
  package.json
  quantum/nodes/hadamard-gate/hadamard-gate.js
  quantum/nodes/not-gate/not-gate.html
  quantum/nodes/not-gate/not-gate.js
  quantum/snippets.js
Labels: enhancement

#30 Communicating the number of qubits from circuit start to output nodes
  quantum/nodes/classical-register/classical-register.js
  quantum/nodes/quantum-circuit/quantum-circuit.html
  quantum/nodes/quantum-circuit/quantum-circuit.js
  quantum/nodes/quantum-register/quantum-register.js
  quantum/nodes/toffoli-gate/toffoli-gate.js
  quantum/snippets.js
Labels: enhancement

#24 Simulator node
  package.json
  quantum/errors.js
  quantum/nodes/classical-register/classical-register.html
  quantum/nodes/classical-register/classical-register.js
  quantum/nodes/measurement/measurement.html
  quantum/nodes/measurement/measurement.js
  quantum/nodes/quantum-circuit/quantum-circuit.html
  quantum/nodes/quantum-circuit/quantum-circuit.js
  quantum/nodes/quantum-register/quantum-register.html
  quantum/nodes/quantum-register/quantum-register.js
  quantum/nodes/simulator/simulator.html
  quantum/nodes/simulator/simulator.js
  quantum/snippets.js
Labels: enhancement

#26 Communication logic between classical registers and measurement nodes
  quantum/nodes/classical-register/classical-register.html
  quantum/nodes/classical-register/classical-register.js
  quantum/nodes/measurement/measurement.html
  quantum/nodes/measurement/measurement.js
  quantum/nodes/quantum-circuit/quantum-circuit.html
  quantum/nodes/quantum-circuit/quantum-circuit.js
  quantum/nodes/quantum-register/quantum-register.html
  quantum/nodes/quantum-register/quantum-register.js
Labels: enhancement, refactoring

#33 Louis/parallel-nodes-fixes
  quantum/nodes/barrier/barrier.js
  quantum/nodes/classical-register/classical-register.js
  quantum/nodes/cnot-gate/cnot-gate.js
  quantum/nodes/hadamard-gate/hadamard-gate.js
  quantum/nodes/measurement/measurement.html
  quantum/nodes/measurement/measurement.js
  quantum/nodes/not-gate/not-gate.js
  quantum/nodes/quantum-circuit/quantum-circuit.js
  quantum/nodes/quantum-register/quantum-register.js
  quantum/nodes/simulator/simulator.html
  quantum/nodes/simulator/simulator.js
  quantum/nodes/toffoli-gate/toffoli-gate.js
  quantum/python.js
  quantum/snippets.js
Labels: bug

#37 Deleting runtime storage variables upon output
  quantum/nodes/barrier/barrier.js
  quantum/nodes/cnot-gate/cnot-gate.js
  quantum/nodes/simulator/simulator.js
  quantum/nodes/toffoli-gate/toffoli-gate.js
Labels: bug

#40 Theo/identity and qubit nodes
  package.json
  quantum/nodes/identity/identity.html
  quantum/nodes/identity/identity.js
  quantum/nodes/not-gate/not-gate.html
  quantum/nodes/not-gate/not-gate.js
  quantum/nodes/qubit/qubit.html
  quantum/nodes/qubit/qubit.js
  quantum/snippets.js
Labels: enhancement

#43 Theo/Reset, Phase gate, XYZ Rotations gate & U gate nodes
  package.json
  quantum/nodes/phase-gate/phase-gate.html
  quantum/nodes/phase-gate/phase-gate.js
  quantum/nodes/reset/reset.html
  quantum/nodes/reset/reset.js
  quantum/nodes/rotation-gate/rotation-gate.html
  quantum/nodes/rotation-gate/rotation-gate.js
  quantum/nodes/u-gate/u-gate.html
  quantum/nodes/u-gate/u-gate.js
  quantum/snippets.js
Labels: enhancement

#45 Fixed issue #39 by removing an extra iteration
  quantum/nodes/cnot-gate/cnot-gate.js
  quantum/nodes/toffoli-gate/toffoli-gate.js
Labels: bug

#46 Louis/unit-tests
  .github/workflows/node.js.yml
  package-lock.json
  package.json
  quantum/python.js
  test/python.test.js
Labels: bug, enhancement

#50 Louis/update-readme
  README.md
  test/python.test.js
Labels: documentation

#48 Theo/Nodes input validation & error handling
  quantum/errors.js
  quantum/nodes/barrier/barrier.js
  quantum/nodes/classical-register/classical-register.js
  quantum/nodes/cnot-gate/cnot-gate.js
  quantum/nodes/hadamard-gate/hadamard-gate.js
  quantum/nodes/identity-gate/identity-gate.js
  quantum/nodes/measure/measure.js
  quantum/nodes/not-gate/not-gate.js
  quantum/nodes/phase-gate/phase-gate.js
  quantum/nodes/quantum-circuit/quantum-circuit.js
  quantum/nodes/quantum-register/quantum-register.js
  quantum/nodes/qubit/qubit.js
  quantum/nodes/reset/reset.js
  quantum/nodes/rotation-gate/rotation-gate.js
  quantum/nodes/simulator/simulator.js
  quantum/nodes/swap/swap.js
  quantum/nodes/toffoli-gate/toffoli-gate.js
  quantum/nodes/unitary-gate/unitary-gate.js
Labels: enhancement, refactoring

#51 Rudimentary documentation of nodes for ease of use
  quantum/nodes/barrier/barrier.html
  quantum/nodes/classical-register/classical-register.html
  quantum/nodes/cnot-gate/cnot-gate.html
  quantum/nodes/execute/execute.html
  quantum/nodes/hadamard-gate/hadamard-gate.html
  quantum/nodes/identity-gate/identity-gate.html
  quantum/nodes/measure/measure.html
  quantum/nodes/not-gate/not-gate.html
  quantum/nodes/phase-gate/phase-gate.html
  quantum/nodes/quantum-circuit/quantum-circuit.html
  quantum/nodes/quantum-register/quantum-register.html
  quantum/nodes/qubit/qubit.html
  quantum/nodes/reset/reset.html
  quantum/nodes/rotation-gate/rotation-gate.html
  quantum/nodes/simulator/simulator.html
  quantum/nodes/swap/swap.html
  quantum/nodes/toffoli-gate/toffoli-gate.html
  quantum/nodes/unitary-gate/unitary-gate.html
Labels: documentation

#38 Fix quantum circuit initialisation
  package-lock.json
  package.json
  quantum/nodes/classical-register/classical-register.js
  quantum/nodes/hadamard-gate/hadamard-gate.js
  quantum/nodes/identity-gate/identity-gate.js
  quantum/nodes/quantum-circuit/quantum-circuit.js
  quantum/nodes/quantum-register/quantum-register.js
  quantum/nodes/simulator/simulator.js
  quantum/python.js
Labels: bug

#49 Louis/script-node
  package.json
  quantum/nodes/execute/execute.html
  quantum/nodes/execute/execute.js
  quantum/nodes/script/script.html
  quantum/nodes/script/script.js
Labels: enhancement
