Repository node-red-quantum/node-red-contrib-quantum, pull requests merged in 2021-09, with the labels that each got.

#111 Louis/python-migration
  README.md
  nodes/python.js
  nodes/quantum-algorithms/grovers/grovers.js
  nodes/quantum-algorithms/shors/shors.js
  nodes/quantum/barrier/barrier.js
  nodes/quantum/bloch-sphere/bloch-sphere.js
  nodes/quantum/circuit-diagram/circuit-diagram.js
  nodes/quantum/classical-register/classical-register.js
  nodes/quantum/cnot-gate/cnot-gate.js
  nodes/quantum/controlled-u-gate/controlled-u-gate.js
  nodes/quantum/hadamard-gate/hadamard-gate.js
  nodes/quantum/histogram-simulator/histogram-simulator.js
  nodes/quantum/ibm-quantum-system/ibm-quantum-system.js
  nodes/quantum/identity-gate/identity-gate.js
  nodes/quantum/local-simulator/local-simulator.js
  nodes/quantum/measure/measure.js
  nodes/quantum/multi-controlled-u-gate/multi-controlled-u-gate.js
  nodes/quantum/not-gate/not-gate.js
  nodes/quantum/phase-gate/phase-gate.js
  nodes/quantum/quantum-circuit/quantum-circuit.js
  nodes/quantum/quantum-register/quantum-register.js
  nodes/quantum/reset/reset.js
  nodes/quantum/rotation-gate/rotation-gate.js
  nodes/quantum/script/script.js
  nodes/quantum/swap/swap.js
  nodes/quantum/toffoli-gate/toffoli-gate.js
  nodes/quantum/unitary-gate/unitary-gate.js
  package-lock.json
  package.json
  test/nodes/script_spec.js
  test/python_spec.js
Labels: enhancement

#116 Documentation - README & Wiki
  README.md
  nodes/quantum-algorithms/grovers/locales/en-US/grovers.html
  nodes/quantum-algorithms/shors/locales/en-US/shors.html
  nodes/quantum/ibm-quantum-system/locales/en-US/ibm-quantum-system.html
  resources/quantum-algorithms-nodes/quantum-algorithms-palette.png
  resources/quantum-algorithms-nodes/shors/input.png
  resources/quantum-algorithms-nodes/shors/node-appearance.png
  resources/quantum-algorithms-nodes/shors/output.png
Labels: documentation

#115 Rui/update circuit init logic
  nodes/quantum/classical-register/classical-register.js
  nodes/quantum/quantum-circuit/quantum-circuit.js
  nodes/quantum/quantum-register/quantum-register.js
  test/nodes/classical-register_spec.js
  test/nodes/quantum-register_spec.js
Labels: refactoring

#119 Timur/more tests
  nodes/quantum/classical-register/classical-register.js
  test/nodes/barrier_spec.js
  test/nodes/bloch-sphere_spec.js
  test/nodes/circuit-diagram_spec.js
  test/nodes/cnot-gate_spec.js
  test/nodes/controlled-u-gate_spec.js
  test/nodes/identity-gate_spec.js
  test/nodes/local-simulator_spec.js
  test/nodes/not-gate_spec.js
  test/nodes/phase-gate_spec.js
  test/nodes/quantum-circuit_spec.js
  test/nodes/quantum-register_spec.js
  test/nodes/qubit_spec.js
  test/nodes/rotation-gate_spec.js
  test/nodes/script_spec.js
  test/nodes/swap_spec.js
  test/nodes/toffoli-gate_spec.js
  test/nodes/unitary-gate_spec.js
Labels: enhancement

#122 Louis/ci-fixes
  .github/workflows/node.js.yml
  nodes/logger.js
  nodes/quantum-algorithms/grovers/grovers.js
  package-lock.json
  package.json
  test/nodes/bloch-sphere_spec.js
  test/nodes/circuit-diagram_spec.js
  test/python_spec.js
Labels: bug

#98 Chon/fc portfolio optimisation
  bin/pyvenv.ps1
  bin/pyvenv.sh
  nodes/quantum-algorithms/portfolio-optimisation/locales/en-US/portfolio-optimisation.html
  nodes/quantum-algorithms/portfolio-optimisation/portfolio-optimisation.html
  nodes/quantum-algorithms/portfolio-optimisation/portfolio-optimisation.js
  nodes/quantum-algorithms/shors/shors.html
  nodes/snippets.js
  package.json
Labels: enhancement

#54 Rui/docker support
  .dockerignore
  Dockerfile.dev
  Dockerfile.prod
  README.md
  bin/start-dev-container.sh
  docker-compose.yml
Labels: enhancement

#125 Louis/bug-fixes
  .github/workflows/node.js.yml
  nodes/quantum/classical-register/classical-register.js
  nodes/quantum/quantum-register/quantum-register.js
  package-lock.json
  package.json
  test/flow-builder.js
  test/nodes/histogram-simulator_spec.js
  test/nodes/multi-controlled-u-gate_spec.js
  test/nodes/not-gate_spec.js
  test/nodes/portfolio-optimisation_spec.js
Labels: bug
