Repository node-red-quantum/node-red-contrib-quantum, pull requests merged in 2021-08, with the labels that each got.

#57 Louis/pythonshell-fixes
  .github/workflows/codeql-analysis.yml
  .github/workflows/node.js.yml
  package-lock.json
  package.json
  quantum/python.js
  test/python.test.js
Labels: bug, enhancement

#60 Louis/bug-fixes
  quantum/nodes/barrier/barrier.js
  quantum/nodes/cnot-gate/cnot-gate.js
  quantum/nodes/not-gate/not-gate.js
  quantum/nodes/phase-gate/phase-gate.js
  quantum/nodes/reset/reset.js
  quantum/nodes/rotation-gate/rotation-gate.js
  quantum/nodes/simulator/simulator.js
  quantum/nodes/swap/swap.js
  quantum/nodes/toffoli-gate/toffoli-gate.js
  quantum/nodes/unitary-gate/unitary-gate.js
  test/python.test.js
Labels: bug

#62 Khesim/ibm quantum connection
  package.json
  quantum/nodes/ibm-quantum-system/ibm-quantum-system.html
  quantum/nodes/ibm-quantum-system/ibm-quantum-system.js
  quantum/nodes/local-simulator/local-simulator.html
  quantum/nodes/local-simulator/local-simulator.js
  quantum/snippets.js
Labels: enhancement

#65 Louis/node-unit-tests
  README.md
  package-lock.json
  package.json
  quantum/nodes/ibm-quantum-system/ibm-quantum-system.js
  quantum/nodes/local-simulator/local-simulator.js
  test/nodes/barrier_spec.js
  test/nodes/classical-register_spec.js
  test/nodes/cnot-gate_spec.js
  test/nodes/hadamard-gate_spec.js
  test/nodes/ibm-quantum-system_spec.js
  test/nodes/identity-gate_spec.js
  test/nodes/local-simulator_spec.js
  test/nodes/measure_spec.js
  test/nodes/not-gate_spec.js
  test/nodes/phase-gate_spec.js
  test/nodes/quantum-circuit_spec.js
  test/nodes/quantum-register_spec.js
  test/nodes/qubit_spec.js
  test/nodes/reset_spec.js
  test/nodes/rotation-gate_spec.js
  test/nodes/script_spec.js
  test/nodes/swap_spec.js
  test/nodes/toffoli-gate_spec.js
  test/nodes/unitary-gate_spec.js
  test/python_spec.js
  test/test-util.js
Labels: enhancement

#61 Theo/Documentation
  quantum/nodes/barrier/barrier.html
  quantum/nodes/barrier/locales/en-US/barrier.html
  quantum/nodes/classical-register/classical-register.html
  quantum/nodes/classical-register/locales/en-US/classical-register.html
  quantum/nodes/cnot-gate/cnot-gate.html
  quantum/nodes/cnot-gate/locales/en-US/cnot-gate.html
  quantum/nodes/hadamard-gate/hadamard-gate.html
  quantum/nodes/hadamard-gate/locales/en-US/hadamard-gate.html
  quantum/nodes/ibm-quantum-system/ibm-quantum-system.html
  quantum/nodes/ibm-quantum-system/locales/en-US/ibm-quantum-system.html
  quantum/nodes/identity-gate/identity-gate.html
  quantum/nodes/identity-gate/locales/en-US/identity-gate.html
  quantum/nodes/local-simulator/local-simulator.html
  quantum/nodes/local-simulator/local-simulator.js
  quantum/nodes/local-simulator/locales/en-US/local-simulator.html
  quantum/nodes/measure/locales/en-US/measure.html
  quantum/nodes/measure/measure.html
  quantum/nodes/not-gate/locales/en-US/not-gate.html
  quantum/nodes/not-gate/not-gate.html
  quantum/nodes/phase-gate/locales/en-US/phase-gate.html
  quantum/nodes/phase-gate/phase-gate.html
  quantum/nodes/quantum-circuit/locales/en-US/quantum-circuit.html
  quantum/nodes/quantum-circuit/quantum-circuit.html
  quantum/nodes/quantum-register/locales/en-US/quantum-register.html
  quantum/nodes/quantum-register/quantum-register.html
  quantum/nodes/qubit/locales/en-US/qubit.html
  quantum/nodes/qubit/qubit.html
  quantum/nodes/reset/locales/en-US/reset.html
  quantum/nodes/reset/reset.html
  quantum/nodes/rotation-gate/locales/en-US/rotation-gate.html
  quantum/nodes/rotation-gate/rotation-gate.html
  quantum/nodes/script/locales/en-US/script.html
  quantum/nodes/script/script.html
  quantum/nodes/swap/locales/en-US/swap.html
  quantum/nodes/swap/swap.html
  quantum/nodes/toffoli-gate/locales/en-US/toffoli-gate.html
  quantum/nodes/toffoli-gate/toffoli-gate.html
  quantum/nodes/unitary-gate/locales/en-US/unitary-gate.html
  quantum/nodes/unitary-gate/unitary-gate.html
Labels: documentation

#64 Theo/Controlled Unitary gate
  package.json
  quantum/errors.js
  quantum/nodes/cnot-gate/cnot-gate.html
  quantum/nodes/controlled-u-gate/controlled-u-gate.html
  quantum/nodes/controlled-u-gate/controlled-u-gate.js
  quantum/nodes/ibm-quantum-system/ibm-quantum-system.js
  quantum/nodes/measure/measure.html
  quantum/nodes/quantum-circuit/quantum-circuit.js
  quantum/nodes/quantum-register/quantum-register.js
  quantum/nodes/toffoli-gate/toffoli-gate.html
  quantum/snippets.js
Labels: enhancement

#68 Theo/small var scope error
  quantum/nodes/quantum-circuit/quantum-circuit.js
  quantum/nodes/quantum-register/quantum-register.js
Labels: bug

#69 Hadamard gate typo fixed
  quantum/nodes/hadamard-gate/hadamard-gate.js
Labels: bug

#70 Theo/README.md draft
  AUTHORS
  CHANGELOG.md
  README.md
  images/QuantumRandomNumber.png
  package.json
Labels: documentation

#71 Louis/update-setup-script
  bin/pyvenv.sh
  package.json
Labels: enhancement

#73 Louis/pythonpath-fix
  package-lock.json
  package.json
  quantum/python.js
  test/python_spec.js
Labels: bug

#75 Louis/contributing
  .github/workflows/codeql-analysis.yml
  .github/workflows/node.js.yml
  CONTRIBUTING.md
  README.md
Labels: documentation

#76 Theo/front end
  quantum/nodes/circuit-diagram/locales/en-US/circuit-diagram.html
  quantum/nodes/controlled-u-gate/controlled-u-gate.html
  quantum/nodes/controlled-u-gate/locales/en-US/controlled-u-gate.html
  quantum/nodes/local-simulator/locales/en-US/local-simulator.html
  quantum/nodes/phase-gate/phase-gate.html
  quantum/nodes/rotation-gate/rotation-gate.html
  quantum/nodes/unitary-gate/unitary-gate.html
Labels: enhancement

#82 Louis/global-state
  quantum/errors.js
  quantum/nodes/classical-register/classical-register.js
  quantum/nodes/quantum-circuit/quantum-circuit.js
  quantum/nodes/quantum-register/quantum-register.js
  quantum/state.js
Labels: bug, enhancement

#79 Grover's algorithm node
  package-lock.json
  package.json
  quantum/errors.js
  quantum/nodes/grovers/grovers.html
  quantum/nodes/grovers/grovers.js
  quantum/nodes/grovers/locales/en-US/grovers.html
  quantum/python.js
  quantum/snippets.js
  test/nodes/grovers_spec.js
Labels: enhancement

#85 Theo/documentation 2
  package.json
  quantum/nodes/barrier/locales/en-US/barrier.html
  quantum/nodes/bloch-sphere/locales/en-US/bloch-sphere.html
  quantum/nodes/circuit-diagram/circuit-diagram.js
  quantum/nodes/circuit-diagram/locales/en-US/circuit-diagram.html
  quantum/nodes/classical-register/locales/en-US/classical-register.html
  quantum/nodes/cnot-gate/locales/en-US/cnot-gate.html
  quantum/nodes/controlled-u-gate/locales/en-US/controlled-u-gate.html
  quantum/nodes/grovers/locales/en-US/grovers.html
  quantum/nodes/hadamard-gate/hadamard-gate.html
  quantum/nodes/hadamard-gate/locales/en-US/hadamard-gate.html
  quantum/nodes/ibm-quantum-system/locales/en-US/ibm-quantum-system.html
  quantum/nodes/identity-gate/identity-gate.js
  quantum/nodes/identity-gate/locales/en-US/identity-gate.html
  quantum/nodes/local-simulator/locales/en-US/local-simulator.html
  quantum/nodes/measure/locales/en-US/measure.html
  quantum/nodes/multi-controlled-u-gate/locales/en-US/multi-controlled-u-gate.html
  quantum/nodes/not-gate/locales/en-US/not-gate.html
  quantum/nodes/not-gate/not-gate.js
  quantum/nodes/phase-gate/locales/en-US/phase-gate.html
  quantum/nodes/phase-gate/phase-gate.html
  quantum/nodes/quantum-circuit/locales/en-US/quantum-circuit.html
  quantum/nodes/quantum-circuit/quantum-circuit.html
  quantum/nodes/quantum-register/locales/en-US/quantum-register.html
  quantum/nodes/qubit/locales/en-US/qubit.html
  quantum/nodes/reset/locales/en-US/reset.html
  quantum/nodes/rotation-gate/locales/en-US/rotation-gate.html
  quantum/nodes/script/locales/en-US/script.html
  quantum/nodes/swap/locales/en-US/swap.html
  quantum/nodes/toffoli-gate/locales/en-US/toffoli-gate.html
  quantum/nodes/unitary-gate/locales/en-US/unitary-gate.html
  templates/node-templates/multi-qubits-quantum-gate-template/locales/en-US/multi-qubits-quantum-gate-template.html
  templates/node-templates/quantum-output-node-template/locales/en-US/quantum-output-node-template.html
  templates/node-templates/single-qubit-quantum-gate-template/locales/en-US/single-qubit-quantum-gate-template.html
  test/nodes/grovers_spec.js
Labels: documentation

#103 bug fix #87
  nodes/quantum/quantum-circuit/quantum-circuit.js
  nodes/quantum/quantum-register/quantum-register.js
Labels: bug

#104 louis/metadata-updates
  CONTRIBUTING.md
  README.md
  nodes/quantum/quantum-circuit/locales/en-US/quantum-circuit.html
  package.json
Labels: bug

#105 More unit tests, fixes for some failing unit tests
  nodes/errors.js
  package-lock.json
  test/nodes/barrier_spec.js
  test/nodes/bloch-sphere_spec.js
  test/nodes/circuit-diagram_spec.js
  test/nodes/classical-register_spec.js
  test/nodes/cnot-gate_spec.js
  test/nodes/controlled-u-gate_spec.js
  test/nodes/grovers_spec.js
  test/nodes/hadamard-gate_spec.js
  test/nodes/ibm-quantum-system_spec.js
  test/nodes/identity-gate_spec.js
  test/nodes/local-simulator_spec.js
  test/nodes/measure_spec.js
  test/nodes/multi-controlled-u-gate_spec.js
  test/nodes/not-gate_spec.js
  test/nodes/phase-gate_spec.js
  test/nodes/quantum-register_spec.js
  test/nodes/qubit_spec.js
  test/nodes/reset_spec.js
  test/nodes/rotation-gate_spec.js
  test/nodes/script_spec.js
  test/nodes/shors_spec.js
  test/nodes/swap_spec.js
  test/nodes/toffoli-gate_spec.js
  test/nodes/unitary-gate_spec.js
  test/test-util.js
Labels: enhancement

#92 Rui/connect external program
  nodes/quantum/classical-register/classical-register.js
  nodes/quantum/quantum-circuit/quantum-circuit.js
  nodes/quantum/quantum-register/quantum-register.js
  nodes/snippets.js
  test/nodes/classical-register_spec.js
  test/nodes/measure_spec.js
Labels: enhancement

#110 Louis/more-pyvenv
  .github/workflows/node.js.yml
  bin/pyvenv.sh
Labels: bug

#114 Rui/bug fix
  nodes/quantum/classical-register/classical-register.js
  nodes/quantum/quantum-register/quantum-register.js
  test/nodes/classical-register_spec.js
  test/nodes/quantum-register_spec.js
Labels: bug
